# 機械学習ことはじめ①
目的:
 - ハイパーパラメタチューニング、Nested cross validation, Hold out testの流れを見る
 - ハイパラチューニングで何が変わるかを眺める  
&nbsp;  
  
動かし方:
1. Google Colab https://colab.research.google.com/ を開く
1. 左上の「ファイル」から「ノートブックを開く」を選択する
1. 開いたウィンドウの左メニューから「GitHub」を選択する
1. URLの欄にGitHubにおけるノートブックのURLを入れる
1. Google Colab上でノートブックが開けたらそれを実行する

## 準備

### 各種依存関係のインストール

In [1]:
#@title Dependencies
import sys
import pandas as pd
import numpy as np

from functools import partial

import sklearn
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score, classification_report
from sklearn.model_selection import cross_validate, train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

!pip install optuna
import optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

### 公共データの取得
https://www.openml.org/search?type=data&sort=runs&id=5&status=active  
年齢、性別、身長、体重、心電図の各指標（すごくたくさんある）、心電図診断  
`class`に心電図診断が入っていて、これを目的変数にします  
今回は虚血性心疾患を見つけることを目的にしてみましょう

In [11]:
#@title OpenML `arrhythmia` data
data = fetch_openml(data_id=5, as_frame=True, parser='auto').frame
(data)

,age,sex,height,weight,QRSduration,PRinterval,Q-Tinterval,Tinterval,Pinterval,QRS,...,chV6_QwaveAmp,chV6_RwaveAmp,chV6_SwaveAmp,chV6_RPwaveAmp,chV6_SPwaveAmp,chV6_PwaveAmp,chV6_TwaveAmp,chV6_QRSA,chV6_QRSTA,class
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1
451,78,1,160,70,79,127,364,138,78,28,...,0.0,10.4,-1.8,0.0,0.0,0.5,1.6,21.3,32.8,1

### 前処理 (Preprocessing)  
やっていること  
1. 欠損が "?" で入力されているのでこれを`np.nan`に置き換える  
2. 全部数値に変換、失敗するようなら`Nan`でよい（※ここで元々はfactorだったclassが数値に変換されている）
3. 列名`class`を`target`に変更する（pythonの仕様上、`class`のままだと扱いづらいため）
4. 虚血性心疾患 (2) を`1`, それ以外を`0`に振り分ける
5. データ欠損が5%未満の変数だけ残す
6. それでも残った欠損は雑に中央値で埋める
7. 変動が少ない変数（95%以上の例で値が同じであるような変数）を捨てる
8. 強い相関のある変数（相関係数の絶対値が0.9超）の片方を捨てる  
&nbsp;  

7, 8は実際の仕事でも割とよくやる手順です  
 - データ内でバラツキが少ない変数は入れていても予測に寄与するとは考え難い  
 - 強い相関のある変数同士は片方だけで情報量としては十分  

ただ、閾値や選定基準は本来はもっとデータの意味を考えて決めるものです  
今回は例示用にざっくり削りたいので、適当に閾値を決めて落としています  
&nbsp;  
  
※コードは結構gemini君に訊きながら書いてます  
※正直R, tidyverse環境でやるほうが遥かに楽だと思います  
※余談: https://share.google/aimode/Dj6mlIvlIvyeQluaz

In [3]:
#@title Preprocessing
data_df = data.replace(
        "?", np.nan
    ).apply(
        pd.to_numeric, errors="coerce"
    ).rename(
        columns={"class": "target"}
    ).assign(
        target = lambda x: x["target"].isin([2]).astype(int)
    ).pipe(
        lambda x: x.loc[:, x.isnull().mean() < 0.05]
    ).pipe(
        lambda x: x.fillna(x.median(numeric_only=True))
    ).pipe(
        lambda x: x.loc[:, (x.apply(lambda col: col.value_counts(normalize=True).max()) < 0.95) | (x.columns == "target") ]
    ).pipe(
        lambda x: (
            x.drop(columns=
                x.corr().abs()
                .where(np.triu(np.ones(x.corr().shape), k=1).astype(bool))
                .pipe(lambda df: [c for c in df.columns if any(df[c] > 0.9)])
            )
        )
    )

(data_df)

,age,sex,height,weight,QRSduration,PRinterval,Q-Tinterval,Tinterval,Pinterval,QRS,...,chV5_QRSTA,chV6_JJwaveAmp,chV6_QwaveAmp,chV6_RwaveAmp,chV6_SwaveAmp,chV6_PwaveAmp,chV6_TwaveAmp,chV6_QRSA,chV6_QRSTA,target
0,75,0,190,80,91,193,371,174,121,-16,...,62.9,-0.3,0.0,9.0,-0.9,0.9,2.9,23.3,49.4,0
1,56,1,165,64,81,174,401,149,39,25,...,43.4,-0.5,0.0,8.5,0.0,0.2,2.1,20.4,38.8,0
2,54,0,172,95,138,163,386,185,102,96,...,48.2,0.9,0.0,9.5,-2.4,0.3,3.4,12.3,49.0,0
3,55,0,175,94,100,202,380,179,143,28,...,68.0,0.1,0.0,12.2,-2.2,0.4,2.6,34.6,61.6,0
4,75,0,190,80,88,181,360,177,103,-16,...,48.9,-0.4,0.0,13.1,-3.6,-0.1,3.9,25.4,62.8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,-0.6,0.0,0.0,4.3,-5.0,0.7,0.6,-4.4,-0.5,0
448,37,0,190,85,100,137,361,201,73,86,...,82.5,-0.5,0.0,15.6,-1.6,0.4,2.4,38.0,62.4,0
449,36,0,166,68,108,176,365,194,116,-85,...,-63.6,1.2,0.0,16.3,-28.6,1.5,1.0,-44.2,-33.2,1
450,32,1,155,55,93,106,386,218,63,54,...,61.0,0.2,-0.4,12.0,-0.7,0.5,2.4,25.0,46.6,0
451,78,1,160,70,79,127,364,138,78,28,...,38.9,-0.3,0.0,10.4,-1.8,0.5,1.6,21.3,32.8,0

### ながめてみる
陽性例は452例中44例（9.7%）、不均衡データです  
説明変数はある程度雑に削ったけれどまだ159個残っています

In [4]:
#@title Take a glance
print(sum(data_df["target"] == 1))
print(data_df.columns.values)

44
['age' 'sex' 'height' 'weight' 'QRSduration' 'PRinterval' 'Q-Tinterval'
 'Tinterval' 'Pinterval' 'QRS' 'T' 'P' 'QRST' 'heartrate' 'chDI_Qwave'
 'chDI_Rwave' 'chDI_Swave' 'chDI_intrinsicReflecttions' 'chDII_Qwave'
 'chDII_Rwave' 'chDII_Swave' 'chDII_intrinsicReflecttions' 'chDIII_Qwave'
 'chDIII_Rwave' 'chDIII_Swave' 'chDIII_RPwave'
 'chDIII_intrinsicReflecttions' 'chAVR_Qwave' 'chAVR_Rwave' 'chAVR_Swave'
 'chAVR_RPwave' 'chAVR_intrinsicReflecttions' 'chAVL_Qwave' 'chAVL_Rwave'
 'chAVL_Swave' 'chAVL_intrinsicReflecttions' 'chAVF_Qwave' 'chAVF_Rwave'
 'chAVF_Swave' 'chAVF_intrinsicReflecttions' 'chV1_Qwave' 'chV1_Rwave'
 'chV1_Swave' 'chV1_RPwave' 'chV1_intrinsicReflecttions' 'chV2_Qwave'
 'chV2_Rwave' 'chV2_Swave' 'chV2_RPwave' 'chV2_intrinsicReflecttions'
 'chV3_Qwave' 'chV3_Rwave' 'chV3_Swave' 'chV3_intrinsicReflecttions'
 'chV4_Qwave' 'chV4_Rwave' 'chV4_Swave' 'chV4_intrinsicReflecttions'
 'chV5_Qwave' 'chV5_Rwave' 'chV5_Swave' 'chV5_intrinsicReflecttions'
 'chV6_Qwave' 'chV6_Rwave' 'chV6_Swave' 'chV6_intrinsicReflecttions'
 'chDI_JJwaveAmp' 'chDI_RwaveAmp' 'chDI_SwaveAmp' 'chDI_PwaveAmp'
 'chDI_TwaveAmp' 'chDI_QRSA' 'chDI_QRSTA' 'chDII_JJwaveAmp'
 'chDII_RwaveAmp' 'chDII_SwaveAmp' 'chDII_PwaveAmp' 'chDII_TwaveAmp'
 'chDII_QRSA' 'chDII_QRSTA' 'chDIII_JJwaveAmp' 'chDIII_QwaveAmp'
 'chDIII_RwaveAmp' 'chDIII_SwaveAmp' 'chDIII_RPwaveAmp' 'chDIII_PwaveAmp'
 'chDIII_TwaveAmp' 'chDIII_QRSA' 'chDIII_QRSTA' 'chAVR_JJwaveAmp'
 'chAVR_QwaveAmp' 'chAVR_RwaveAmp' 'chAVR_PwaveAmp' 'chAVR_TwaveAmp'
 'chAVR_QRSA' 'chAVR_QRSTA' 'chAVL_JJwaveAmp' 'chAVL_QwaveAmp'
 'chAVL_RwaveAmp' 'chAVL_SwaveAmp' 'chAVL_PwaveAmp' 'chAVL_TwaveAmp'
 'chAVL_QRSTA' 'chAVF_JJwaveAmp' 'chAVF_QwaveAmp' 'chAVF_SwaveAmp'
 'chAVF_PwaveAmp' 'chAVF_TwaveAmp' 'chAVF_QRSTA' 'chV1_JJwaveAmp'
 'chV1_QwaveAmp' 'chV1_RwaveAmp' 'chV1_SwaveAmp' 'chV1_RPwaveAmp'
 'chV1_PwaveAmp' 'chV1_TwaveAmp' 'chV1_QRSA' 'chV1_QRSTA' 'chV2_JJwaveAmp'
 'chV2_QwaveAmp' 'chV2_RwaveAmp' 'chV2_SwaveAmp' 'chV2_RPwaveAmp'
 'chV2_PwaveAmp' 'chV2_TwaveAmp' 'chV2_QRSA' 'chV2_QRSTA' 'chV3_JJwaveAmp'
 'chV3_QwaveAmp' 'chV3_RwaveAmp' 'chV3_SwaveAmp' 'chV3_PwaveAmp'
 'chV3_TwaveAmp' 'chV3_QRSA' 'chV3_QRSTA' 'chV4_JJwaveAmp' 'chV4_QwaveAmp'
 'chV4_RwaveAmp' 'chV4_SwaveAmp' 'chV4_PwaveAmp' 'chV4_TwaveAmp'
 'chV4_QRSA' 'chV4_QRSTA' 'chV5_JJwaveAmp' 'chV5_QwaveAmp' 'chV5_RwaveAmp'
 'chV5_SwaveAmp' 'chV5_PwaveAmp' 'chV5_TwaveAmp' 'chV5_QRSA' 'chV5_QRSTA'
 'chV6_JJwaveAmp' 'chV6_QwaveAmp' 'chV6_RwaveAmp' 'chV6_SwaveAmp'
 'chV6_PwaveAmp' 'chV6_TwaveAmp' 'chV6_QRSA' 'chV6_QRSTA' 'target']

## 使用する関数などの定義
pythonの仕様上、処理の内側から外側に向かう順で書いていくことになるので  
初学者には非常に読みづらい

### Optunaで最適化する目的関数
以下のもの、
 - Optuna trialなる存在 (`trial`)
 - 説明変数たち (`X`)
 - 目的変数=正解ラベル (`y`)
 - 使うcross validationという物体 (`cv`)  

……を入れると、  
 - `trial`から発生したハイパーパラメータの提案に対して、
 - 与えられた`cv`を使ってcross validationをして、
 - cross validationにおける`neg_log_loss` = -1×LogLossの平均値を返す

……という関数（しくみ）を書いています  
&nbsp;  
  
ハイパラの探索範囲は`param = { ...... }`の中身です  
不均衡データ対策の`class_weight="balanced"`は探索範囲が1種類=実質固定の先決めですが、  
Optunaの文法に入れ込むためにこのような書き方にしています

In [5]:
#@title Objective function for Optuna
def objective_CLF(trial, X, y, cv):
    param = {
        "class_weight": trial.suggest_categorical("class_weight", ["balanced"]),
        "penalty": trial.suggest_categorical("penalty", ["elasticnet"]),
        "C": trial.suggest_float("C", 1e-3, 1e3, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0, 1, step=0.1),
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "max_iter": trial.suggest_categorical("max_iter", [10000]),
        }

    classifier = LogisticRegression()
    classifier.set_params(**param)

    scores = cross_val_score(classifier, X, y, cv=cv, scoring="neg_log_loss")

    return scores.mean()

### Inner CV の関数
以下のもの、
 - 訓練用データの説明変数たち (`train_X`)
 - 訓練用データの目的変数=正解ラベル (`train_y`)
 - 評価用データの説明変数たち (`test_X`)
 - 評価用データの目的変数=正解ラベル (`test_y`)
 - してほしいcross validationの回数 (`n_inner`)
 - してほしいOptunaの試行数 (`n_optuna`)
 - 乱数のシード (`random_state`)

……を入れると、  
 - 訓練用データと各種パラメタからOptuna trialとinner CVを作成して、
 - 先ほど定義した目的関数を計算して、
 - その目的関数を最大化 = `neg_log_loss`を最大化 して、
 - Optunaで探索して決めたハイパーパラメータを使って訓練用データで学習して、
 - 評価用データにおける予測までする

……を経て、
 - 学習済みモデル
 - 探索でみつけた最適なハイパーパラメータ
 - 評価用データでの予測（予測値とスコアの両方）

などを返す

……という関数（しくみ）を書いています

In [6]:
#@title Inner CV function
def innerCV_CLF(train_X, train_y, test_X, test_y, n_inner, n_optuna, random_state):

    # inner CV to use
    cv_inner = StratifiedKFold(n_splits=n_inner, shuffle=True, random_state=random_state)

    # Hyper parameter tuning with inner CV
    study_icv = optuna.create_study(direction="maximize")
    study_icv.optimize(partial(objective_CLF, X=train_X, y=train_y, cv=cv_inner), n_trials = n_optuna, show_progress_bar = False)

    # Learn whole train set with best parameters
    clf_icv = LogisticRegression(**study_icv.best_params).fit(train_X, train_y)

    # Make predictions
    preds_icv  = clf_icv.predict(test_X)
    scores_icv = clf_icv.decision_function(test_X)

    # Take model metrics
    AUROC_icv = roc_auc_score(test_y, scores_icv)

    return {
        "model": "Logistic regression",
        "best_params": study_icv.best_params,
        "classifier": clf_icv,
        "y_true": test_y,
        "y_pred": preds_icv,
        "y_score": scores_icv,
    }

## データの分割
まずNested cross validation (NCV) に使うデータと最終評価 (validation) に使うデータとを切り分けます  
割合はケースバイケース、ここでは10%としました  
正解ラベルの割合に偏りが生じないように`target`での層別化をかけています

In [7]:
#@title Train test split
# Stratified split based on `target` value

data_ncv, data_validation = train_test_split(
    data_df,
    test_size=0.1,
    stratify=data_df["target"],
    random_state=42
)

## Nested cross validation
ここに書いてあるのはouter CV, 外側の周回です  
ハイパラチューニングで使うinnner CVは既に関数の形で書いてあります  
&nbsp;  

各周回ごとに、
 - `cv_outer`で発生する分割（`target`での層別化つき）に沿ってデータを分割する
 - 説明変数について、訓練データ側で標準化を行う（`scaler.fit_transform`）
 - 訓練データにも**同じスケールでの**標準化を適応する（`scaler.transform`）
 - ハイパラチューニングをしない分類器で訓練・予測をする
 - `icv_CLF`で内側の周回を伴うハイパラチューニング、訓練、予測を一気に行う
 - 指標を表示
 - データを`DataFrame`に保存  

 を行っています

In [8]:
#@title Nested cross validation
## Parapeters for ML
n_inner = 5
n_outer = 5
n_optuna = 30

### Data frame to store predictions
ncv_preds_df = pd.DataFrame()

### Outer CV to use
cv_outer = StratifiedKFold(n_splits=n_outer, shuffle=True, random_state=42)

### Scaler
scaler = StandardScaler().set_output(transform="pandas")

### Outer CV
for split, (train_idx, test_idx) in enumerate(cv_outer.split(data_ncv, data_ncv["target"])):

    # Split data according to CV
    data_ncv_train = data_ncv.iloc[train_idx,:]
    data_ncv_test = data_ncv.iloc[test_idx,:]

    # Split data for inner CV (train)
    train_X = scaler.fit_transform(data_ncv_train.drop(columns=["target"]))
    train_y = data_ncv_train["target"]

    # Split data for inner CV (test)
    test_X = scaler.transform(data_ncv_test.drop(columns=["target"]))
    test_y = data_ncv_test["target"]

    # Unpenalized LogisticRegression classifier
    ## Fit the classifier
    CLF_noTuning = LogisticRegression(penalty=None, solver="saga", max_iter=10000).fit(train_X, train_y)

    ## Make predictions
    preds_noTuning  = CLF_noTuning.predict(test_X)
    scores_noTuning = CLF_noTuning.decision_function(test_X)


    # LogisticRegression classifier (elastic net) with tunings
    ## Inner CV
    ## This objective function does hyperparameter tuning, prediction in test set
    icv_CLF = innerCV_CLF(train_X=train_X, train_y=train_y, test_X=test_X, test_y=test_y, n_inner=n_inner, n_optuna=n_optuna, random_state=42)


    # Print results of this fold
    print(f"fold: {split}, classifier: Unpenalized LogisticRegression, AUROC: ", roc_auc_score(test_y, preds_noTuning))
    print(classification_report(test_y, preds_noTuning))
    print(f"fold: {split}, classifier: ElasticNet with tuning, AUROC: ", roc_auc_score(test_y, icv_CLF["y_pred"]))
    print(classification_report(test_y, icv_CLF["y_pred"]))
    print(f"fold: {split}, classifier: ElasticNet with tuning, best_params: ", icv_CLF["best_params"])


    # Store predictions
    ncv_preds_df = pd.concat([
        ncv_preds_df,
        pd.DataFrame({
            "fold": split,
            "classifier": "Unpenalized LogisticRegression",
            "y_index": test_y.index,
            "y_true": test_y,
            "y_pred": preds_noTuning,
            "y_score": scores_noTuning,
        }),
        pd.DataFrame({
            "fold": split,
            "classifier": "ElasticNet with tuning",
            "y_index": test_y.index,
            "y_true": test_y,
            "y_pred": icv_CLF["y_pred"],
            "y_score": icv_CLF["y_score"],
        }),
    ])

[I 2026-05-12 00:20:01,002] A new study created in memory with name: no-name-8e0b61c5-462d-478c-afd9-e3ea675ff339
[I 2026-05-12 00:20:17,488] Trial 0 finished with value: -0.37250970648497467 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.4621090172123514, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.37250970648497467.
[I 2026-05-12 00:20:29,765] Trial 1 finished with value: -0.7442603454286727 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 117.52198636419394, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.37250970648497467.
[I 2026-05-12 00:20:56,547] Trial 2 finished with value: -0.7143376043846886 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 33.75862169767855, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.37250970648497467.
[I 2026-05-12 00:21:05,520] Trial 3 finished with value: -0.3632622712929969 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.4651446504987592, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.3632622712929969.
[I 2026-05-12 00:21:26,752] Trial 4 finished with value: -0.6896553691414499 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 27.40221885825263, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.3632622712929969.
[I 2026-05-12 00:21:34,855] Trial 5 finished with value: -0.5154393102221759 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 2.2101574731136395, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.3632622712929969.
[I 2026-05-12 00:21:40,137] Trial 6 finished with value: -0.34988688236055127 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3414022001641649, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:21:52,663] Trial 7 finished with value: -0.5905641253622275 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 5.3515660947797405, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:21:52,729] Trial 8 finished with value: -0.6941666885880446 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.005643978870057585, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:22:00,750] Trial 9 finished with value: -0.3680229278058351 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3622660089425806, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:22:01,156] Trial 10 finished with value: -0.6388606519549234 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.005096078244304463, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:22:02,864] Trial 11 finished with value: -0.3540960267043708 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.06227234222335829, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:22:04,239] Trial 12 finished with value: -0.3602705022336651 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.042015059899233806, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:22:05,497] Trial 13 finished with value: -0.387625662968403 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.03833831477342918, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 6 with value: -0.34988688236055127.
[I 2026-05-12 00:22:07,590] Trial 14 finished with value: -0.34855713162989777 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.05381162855748983, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 14 with value: -0.34855713162989777.
[I 2026-05-12 00:22:07,678] Trial 15 finished with value: -0.6946975776568406 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0013591343643539085, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 14 with value: -0.34855713162989777.
[I 2026-05-12 00:22:25,089] Trial 16 finished with value: -0.7560957892211284 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 948.1307158938259, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 14 with value: -0.34855713162989777.
[I 2026-05-12 00:22:28,807] Trial 17 finished with value: -0.3388946751414102 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1958122997695946, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 17 with value: -0.3388946751414102.
[I 2026-05-12 00:22:31,267] Trial 18 finished with value: -0.35884640817251584 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.08570927202586925, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 17 with value: -0.3388946751414102.
[I 2026-05-12 00:22:32,087] Trial 19 finished with value: -0.5114822732556095 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.015426937745918978, 'l1_ratio': 0.8, 'solver': 'saga', 'max_iter': 10000}. Best is trial 17 with value: -0.3388946751414102.
[I 2026-05-12 00:22:44,396] Trial 20 finished with value: -0.4748344129569836 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 2.503156824917544, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 17 with value: -0.3388946751414102.
[I 2026-05-12 00:22:47,913] Trial 21 finished with value: -0.3287568098519393 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.10343497410427263, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 21 with value: -0.3287568098519393.
[I 2026-05-12 00:22:51,151] Trial 22 finished with value: -0.3224916113096332 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.13327314765016834, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:22:54,475] Trial 23 finished with value: -0.32449714759984716 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.15888451559256095, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:22:55,218] Trial 24 finished with value: -0.434269313797349 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.011010143079153703, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:23:05,582] Trial 25 finished with value: -0.4431336024345532 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.427791263837507, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:23:09,336] Trial 26 finished with value: -0.32372104854755407 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.15965385424427447, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:23:09,707] Trial 27 finished with value: -0.6599071443445738 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0013841360842675426, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:23:10,829] Trial 28 finished with value: -0.3286903758687147 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.019194637697071464, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.
[I 2026-05-12 00:23:20,608] Trial 29 finished with value: -0.41679364378645545 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.8991883964193353, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 22 with value: -0.3224916113096332.

fold: 0, classifier: Unpenalized LogisticRegression, AUROC:  0.847972972972973
              precision    recall  f1-score   support

           0       0.97      0.95      0.96        74
           1       0.60      0.75      0.67         8

    accuracy                           0.93        82
   macro avg       0.79      0.85      0.81        82
weighted avg       0.94      0.93      0.93        82

fold: 0, classifier: ElasticNet with tuning, AUROC:  0.8969594594594594
              precision    recall  f1-score   support

           0       0.99      0.92      0.95        74
           1       0.54      0.88      0.67         8

    accuracy                           0.91        82
   macro avg       0.76      0.90      0.81        82
weighted avg       0.94      0.91      0.92        82

fold: 0, classifier: ElasticNet with tuning, best_params:  {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.13327314765016834, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}

[I 2026-05-12 00:23:24,422] A new study created in memory with name: no-name-cfbaa4d9-c088-4719-b723-f50db56cde2b
[I 2026-05-12 00:23:27,105] Trial 0 finished with value: -0.3537363345692585 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.015396626398267643, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3537363345692585.
[I 2026-05-12 00:23:46,448] Trial 1 finished with value: -0.6392613230440538 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 799.460674202182, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3537363345692585.
[I 2026-05-12 00:23:46,508] Trial 2 finished with value: -0.6868249985501076 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.00286501571073007, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3537363345692585.
[I 2026-05-12 00:24:00,616] Trial 3 finished with value: -0.6148191673626602 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 65.7442986741769, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3537363345692585.
[I 2026-05-12 00:24:10,298] Trial 4 finished with value: -0.5814393009854433 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 15.973322770607858, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3537363345692585.
[I 2026-05-12 00:24:14,085] Trial 5 finished with value: -0.3012142972394224 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1774374688809459, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 5 with value: -0.3012142972394224.
[I 2026-05-12 00:24:19,626] Trial 6 finished with value: -0.3057604086229911 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.19818560827300097, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 5 with value: -0.3012142972394224.
[I 2026-05-12 00:24:34,503] Trial 7 finished with value: -0.6381906154975887 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 518.0500955508521, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 5 with value: -0.3012142972394224.
[I 2026-05-12 00:24:35,303] Trial 8 finished with value: -0.361946705649477 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0058913678259057975, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 5 with value: -0.3012142972394224.
[I 2026-05-12 00:24:50,155] Trial 9 finished with value: -0.6391858088113817 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 797.72921131155, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 5 with value: -0.3012142972394224.
[I 2026-05-12 00:24:58,720] Trial 10 finished with value: -0.3330490667250257 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.5676464129772618, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 5 with value: -0.3012142972394224.
[I 2026-05-12 00:25:03,095] Trial 11 finished with value: -0.3005362796376185 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.2036967661855689, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:05,586] Trial 12 finished with value: -0.3175848000071779 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.09647460122108188, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:18,419] Trial 13 finished with value: -0.42404689451028876 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 2.8449716227010855, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:20,150] Trial 14 finished with value: -0.36755820668820804 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.04169200061822246, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:32,182] Trial 15 finished with value: -0.4286966144504195 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 2.770453006106247, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:32,244] Trial 16 finished with value: -0.6935314427494748 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0011991930991712852, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:41,761] Trial 17 finished with value: -0.34512693196850985 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.7396953690543826, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:43,107] Trial 18 finished with value: -0.3356547223699054 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.033307814917279556, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 11 with value: -0.3005362796376185.
[I 2026-05-12 00:25:47,470] Trial 19 finished with value: -0.2960777810652401 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.21834557496594645, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:00,826] Trial 20 finished with value: -0.5043419777936738 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 8.31081858600601, 'l1_ratio': 0.8, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:05,666] Trial 21 finished with value: -0.3047750374072862 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.15945837105969576, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:11,357] Trial 22 finished with value: -0.3042164801184768 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3237757099261076, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:25,149] Trial 23 finished with value: -0.390390455878788 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.8555618939249043, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:27,188] Trial 24 finished with value: -0.3241577460587355 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.06317758625649733, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:29,336] Trial 25 finished with value: -0.4260004643307928 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.021847977395775712, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:39,245] Trial 26 finished with value: -0.34153251715674965 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.8173172665093188, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:39,934] Trial 27 finished with value: -0.43010420749434425 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.008550533443213281, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:52,311] Trial 28 finished with value: -0.5264440224308677 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 9.333256249409239, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.
[I 2026-05-12 00:26:58,733] Trial 29 finished with value: -0.31341191831900456 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.28776775162760443, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2960777810652401.

fold: 1, classifier: Unpenalized LogisticRegression, AUROC:  0.4452054794520548
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        73
           1       0.00      0.00      0.00         8

    accuracy                           0.80        81
   macro avg       0.45      0.45      0.45        81
weighted avg       0.80      0.80      0.80        81

fold: 1, classifier: ElasticNet with tuning, AUROC:  0.5839041095890412
              precision    recall  f1-score   support

           0       0.92      0.92      0.92        73
           1       0.25      0.25      0.25         8

    accuracy                           0.85        81
   macro avg       0.58      0.58      0.58        81
weighted avg       0.85      0.85      0.85        81

fold: 1, classifier: ElasticNet with tuning, best_params:  {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.21834557496594645, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}

[I 2026-05-12 00:27:03,176] A new study created in memory with name: no-name-88ff8af2-b5c6-4818-b6f6-856888ef3a14
[I 2026-05-12 00:27:05,845] Trial 0 finished with value: -0.3956179456248168 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.05241502635497612, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3956179456248168.
[I 2026-05-12 00:27:07,184] Trial 1 finished with value: -0.42255560382080865 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.018316247099719355, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3956179456248168.
[I 2026-05-12 00:27:23,834] Trial 2 finished with value: -0.5743330212919127 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 51.361297838864125, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3956179456248168.
[I 2026-05-12 00:27:39,799] Trial 3 finished with value: -0.5756875140537188 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 57.07792196544645, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3956179456248168.
[I 2026-05-12 00:27:43,229] Trial 4 finished with value: -0.3662822047150295 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.07423695641145003, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 4 with value: -0.3662822047150295.
[I 2026-05-12 00:27:56,180] Trial 5 finished with value: -0.4574987339472603 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 6.525329439514964, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 4 with value: -0.3662822047150295.
[I 2026-05-12 00:28:13,979] Trial 6 finished with value: -0.5912305233369602 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 134.0970856502647, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 4 with value: -0.3662822047150295.
[I 2026-05-12 00:28:14,033] Trial 7 finished with value: -0.6905108359584151 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.001018203426964455, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 4 with value: -0.3662822047150295.
[I 2026-05-12 00:28:29,474] Trial 8 finished with value: -0.5561523997784213 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 33.47550702226633, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 4 with value: -0.3662822047150295.
[I 2026-05-12 00:28:44,900] Trial 9 finished with value: -0.5602677615730295 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 35.21258281697928, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 4 with value: -0.3662822047150295.
[I 2026-05-12 00:28:49,121] Trial 10 finished with value: -0.29988646164626004 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.29549022931870295, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.29988646164626004.
[I 2026-05-12 00:28:55,150] Trial 11 finished with value: -0.3077894437955764 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3671625528021183, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.29988646164626004.
[I 2026-05-12 00:29:00,534] Trial 12 finished with value: -0.32991264987232555 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.5933436646709005, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.29988646164626004.
[I 2026-05-12 00:29:07,616] Trial 13 finished with value: -0.3502355122849993 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.8500506668667585, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.29988646164626004.
[I 2026-05-12 00:29:18,318] Trial 14 finished with value: -0.4202756051883128 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 3.1762822047250077, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.29988646164626004.
[I 2026-05-12 00:29:35,402] Trial 15 finished with value: -0.6015579215343616 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 607.6555711017551, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.29988646164626004.
[I 2026-05-12 00:29:39,592] Trial 16 finished with value: -0.28327298993857264 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.21035270175753543, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 16 with value: -0.28327298993857264.
[I 2026-05-12 00:29:40,156] Trial 17 finished with value: -0.503574813418124 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0058167839301534715, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 16 with value: -0.28327298993857264.
[I 2026-05-12 00:29:44,911] Trial 18 finished with value: -0.2790546240660189 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.12733536139822257, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:29:47,211] Trial 19 finished with value: -0.3098395846104741 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0923844927994012, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:29:58,662] Trial 20 finished with value: -0.4492961021189855 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 4.012884164000681, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:02,691] Trial 21 finished with value: -0.28045880648765575 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1746752817730497, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:03,502] Trial 22 finished with value: -0.39827441490457993 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.009443336785214104, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:07,293] Trial 23 finished with value: -0.28839476828530664 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.18887461981103723, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:09,477] Trial 24 finished with value: -0.3264857246220543 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.026879320691831503, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:24,020] Trial 25 finished with value: -0.39311081654364355 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 3.0386431985668723, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:26,658] Trial 26 finished with value: -0.301730359580492 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.11268269923856435, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:27,235] Trial 27 finished with value: -0.5154662417930848 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0033282292986060395, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:37,164] Trial 28 finished with value: -0.3714663120772721 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.6268466225995202, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.
[I 2026-05-12 00:30:38,418] Trial 29 finished with value: -0.3548919839333053 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.03599401430937355, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 18 with value: -0.2790546240660189.

fold: 2, classifier: Unpenalized LogisticRegression, AUROC:  0.827054794520548
              precision    recall  f1-score   support

           0       0.97      0.90      0.94        73
           1       0.46      0.75      0.57         8

    accuracy                           0.89        81
   macro avg       0.72      0.83      0.75        81
weighted avg       0.92      0.89      0.90        81

fold: 2, classifier: ElasticNet with tuning, AUROC:  0.896404109589041
              precision    recall  f1-score   support

           0       0.99      0.92      0.95        73
           1       0.54      0.88      0.67         8

    accuracy                           0.91        81
   macro avg       0.76      0.90      0.81        81
weighted avg       0.94      0.91      0.92        81

fold: 2, classifier: ElasticNet with tuning, best_params:  {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.12733536139822257, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}

[I 2026-05-12 00:30:42,192] A new study created in memory with name: no-name-908feb95-f4dc-481d-b368-d6021142ab20
[I 2026-05-12 00:30:57,444] Trial 0 finished with value: -0.48971824179746903 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 332.7792551905458, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.48971824179746903.
[I 2026-05-12 00:31:10,943] Trial 1 finished with value: -0.41227557577224 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 4.566826775275688, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.41227557577224.
[I 2026-05-12 00:31:16,799] Trial 2 finished with value: -0.2905707150381299 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3440777918418478, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:31:26,326] Trial 3 finished with value: -0.3619336540523105 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.3927804139052924, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:31:40,146] Trial 4 finished with value: -0.4293549341202745 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 11.268123160316035, 'l1_ratio': 0.8, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:31:40,607] Trial 5 finished with value: -0.6767427070245093 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.00856496628443324, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:31:54,608] Trial 6 finished with value: -0.45935377071580596 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 34.17343592336758, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:32:07,190] Trial 7 finished with value: -0.3896972019756425 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 2.0004205186985833, 'l1_ratio': 0.8, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:32:23,266] Trial 8 finished with value: -0.4338019916156992 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 4.859108622931182, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:32:38,614] Trial 9 finished with value: -0.4909506959992049 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 523.1313273773915, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 2 with value: -0.2905707150381299.
[I 2026-05-12 00:32:39,921] Trial 10 finished with value: -0.2546441058437247 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.03873679106508225, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:32:41,416] Trial 11 finished with value: -0.2694398242564203 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.047539057540907585, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:32:42,488] Trial 12 finished with value: -0.26592423937921617 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.02376367883701478, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-05-12 00:32:51,136] Trial 13 finished with value: -0.45089650486649013 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.001333675912805842, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:32:53,381] Trial 14 finished with value: -0.26932964398046577 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.10817209257465285, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:32:54,289] Trial 15 finished with value: -0.2800917236083277 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.01590033265783715, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:32:54,384] Trial 16 finished with value: -0.6865579834615512 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0017025773474291424, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:33:00,037] Trial 17 finished with value: -0.27244646027265845 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.2677001569696965, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:33:00,546] Trial 18 finished with value: -0.44407259291491785 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.01022140087647521, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 10 with value: -0.2546441058437247.
[I 2026-05-12 00:33:01,867] Trial 19 finished with value: -0.2545524158044986 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.03886615478189183, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2545524158044986.
[I 2026-05-12 00:33:04,887] Trial 20 finished with value: -0.2709345967783324 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.17279402360002702, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 19 with value: -0.2545524158044986.
[I 2026-05-12 00:33:06,394] Trial 21 finished with value: -0.25076232432528983 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.053218815668859706, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 21 with value: -0.25076232432528983.
[I 2026-05-12 00:33:06,921] Trial 22 finished with value: -0.4541314145248923 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.004505242606270589, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 21 with value: -0.25076232432528983.
[I 2026-05-12 00:33:08,499] Trial 23 finished with value: -0.25020993508596245 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.05779068701127484, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.
[I 2026-05-12 00:33:11,451] Trial 24 finished with value: -0.26072427795330555 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.07333258003523163, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.
[I 2026-05-12 00:33:17,151] Trial 25 finished with value: -0.30110813279150206 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.46468814928171726, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.
[I 2026-05-12 00:33:17,729] Trial 26 finished with value: -0.36838896684933037 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0035395643976075014, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.
[I 2026-05-12 00:33:25,894] Trial 27 finished with value: -0.31631509908748356 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.7438183716870945, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.
[I 2026-05-12 00:33:28,008] Trial 28 finished with value: -0.28112418183949195 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1171455323459368, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.
[I 2026-05-12 00:33:42,702] Trial 29 finished with value: -0.47788047226123104 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 78.69524234862394, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.25020993508596245.

fold: 3, classifier: Unpenalized LogisticRegression, AUROC:  0.6464041095890412
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        73
           1       0.33      0.38      0.35         8

    accuracy                           0.86        81
   macro avg       0.63      0.65      0.64        81
weighted avg       0.87      0.86      0.87        81

fold: 3, classifier: ElasticNet with tuning, AUROC:  0.8065068493150684
              precision    recall  f1-score   support

           0       0.97      0.86      0.91        73
           1       0.38      0.75      0.50         8

    accuracy                           0.85        81
   macro avg       0.67      0.81      0.71        81
weighted avg       0.91      0.85      0.87        81

fold: 3, classifier: ElasticNet with tuning, best_params:  {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.05779068701127484, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}

[I 2026-05-12 00:33:46,186] A new study created in memory with name: no-name-41778838-c2e3-4521-98f0-d65ddce62494
[I 2026-05-12 00:33:57,916] Trial 0 finished with value: -0.42912947272864965 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 3.532198158007401, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.42912947272864965.
[I 2026-05-12 00:34:00,754] Trial 1 finished with value: -0.28956263005317406 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.14347576596706754, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:34:00,817] Trial 2 finished with value: -0.687883510681867 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.001957864250520013, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:34:10,772] Trial 3 finished with value: -0.39609795105877554 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 2.001608333915038, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:34:13,844] Trial 4 finished with value: -0.41257888061187886 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.048249484726962714, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:34:31,706] Trial 5 finished with value: -0.6397251993588526 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 710.7891691606, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:34:46,095] Trial 6 finished with value: -0.5744576142370068 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 23.901770606296168, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:34:47,176] Trial 7 finished with value: -0.33025744311651184 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.018047098531307395, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:35:00,655] Trial 8 finished with value: -0.3829190293959404 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.6004298311043097, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:35:01,233] Trial 9 finished with value: -0.527895500295638 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.010468140469395676, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:35:05,151] Trial 10 finished with value: -0.356117799610955 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1716697368826466, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:35:06,972] Trial 11 finished with value: -0.34351997169082454 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.032468458663734046, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:35:07,831] Trial 12 finished with value: -0.47953395492862044 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0012889666999400628, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 1 with value: -0.28956263005317406.
[I 2026-05-12 00:35:11,179] Trial 13 finished with value: -0.28955954100990194 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1428176050159452, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:35:15,708] Trial 14 finished with value: -0.30653405894130836 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.27162168096688044, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:35:30,565] Trial 15 finished with value: -0.5690741080134274 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 25.20253872623526, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:35:35,995] Trial 16 finished with value: -0.29756983723682795 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.29575864749530717, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:35:50,207] Trial 17 finished with value: -0.5735960512015689 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 20.97613434674424, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:35:53,862] Trial 18 finished with value: -0.3614027079683314 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.13617572215376605, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:06,548] Trial 19 finished with value: -0.5109915558969458 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 8.370603249752305, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:06,895] Trial 20 finished with value: -0.6837084411675333 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.005129068117409976, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:12,555] Trial 21 finished with value: -0.3113524603123922 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.4692732077571102, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:15,428] Trial 22 finished with value: -0.3090479213461063 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.08099493852457243, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:20,528] Trial 23 finished with value: -0.3216942819735882 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.5845075603453624, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:22,701] Trial 24 finished with value: -0.3132781200082339 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.07131726980276802, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:29,238] Trial 25 finished with value: -0.339862763012056 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.7828405550566713, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:45,251] Trial 26 finished with value: -0.6288096809207387 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 134.42778203512725, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:45,817] Trial 27 finished with value: -0.5065131623787826 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.008127850500137843, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:36:50,708] Trial 28 finished with value: -0.29818810814389984 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.2434930956257151, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.
[I 2026-05-12 00:37:02,251] Trial 29 finished with value: -0.4489485102770649 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 4.487322174734565, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 13 with value: -0.28955954100990194.

fold: 4, classifier: Unpenalized LogisticRegression, AUROC:  0.7851027397260274
              precision    recall  f1-score   support

           0       0.96      0.95      0.95        73
           1       0.56      0.62      0.59         8

    accuracy                           0.91        81
   macro avg       0.76      0.79      0.77        81
weighted avg       0.92      0.91      0.92        81

fold: 4, classifier: ElasticNet with tuning, AUROC:  0.952054794520548
              precision    recall  f1-score   support

           0       1.00      0.90      0.95        73
           1       0.53      1.00      0.70         8

    accuracy                           0.91        81
   macro avg       0.77      0.95      0.82        81
weighted avg       0.95      0.91      0.92        81

fold: 4, classifier: ElasticNet with tuning, best_params:  {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.1428176050159452, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}

## 最終モデルの学習と評価
 - NCVに使ったデータ (90%)を学習データにする
 - 説明変数について、訓練データ側で標準化を行う（`scaler.fit_transform`）
 - 訓練データにも**同じスケールでの**標準化を適応する（`scaler.transform`）
 - ハイパラチューニングをしない分類器で学習・予測をする
 - `icv_CLF`で内側の周回を伴うハイパラチューニング、訓練、予測を一気に行う
 - 指標を表示する
 - データを`DataFrame`に保存  

を行っています  
外側のCVがなくなっただけで、ほかはNCVの内側と一緒です

In [9]:
#@title Final modeling

### Parapeters for ML
n_inner = 5
# n_outer = 5 # No longer doing outer CV
n_optuna = 30

### Data frame to store predictions
val_preds_df = pd.DataFrame()

### Scaler
scaler = StandardScaler().set_output(transform="pandas")

### Data for inner CV (data used for NCV)
train_X = scaler.fit_transform(data_ncv.drop(columns=["target"]))
train_y = data_ncv["target"]

### Data for inner CV (data held out for validation)
test_X = scaler.transform(data_validation.drop(columns=["target"]))
test_y = data_validation["target"]

### Unpenalized LogisticRegression
#### Fit the classifier
CLF_noTuning = LogisticRegression(penalty=None, solver="saga", max_iter=10000).fit(train_X, train_y)

#### Make predictions
preds_noTuning  = CLF_noTuning.predict(test_X)
scores_noTuning = CLF_noTuning.decision_function(test_X)


### LogisticRegression classifier (elastic net) with tunings
#### Inner CV
#### This objective function does hyperparameter tuning, prediction in test set
icv_CLF = innerCV_CLF(train_X=train_X, train_y=train_y, test_X=test_X, test_y=test_y, n_inner=n_inner, n_optuna=n_optuna, random_state=42)


### Print results
print(f"fold: {split}, classifier: Unpenalized LogisticRegression, AUROC: ", roc_auc_score(test_y, preds_noTuning))
print(classification_report(test_y, preds_noTuning))
print(f"fold: {split}, classifier: ElasticNet with tuning, AUROC: ", roc_auc_score(test_y, icv_CLF["y_pred"]))
print(classification_report(test_y, icv_CLF["y_pred"]))
print(f"fold: {split}, classifier: ElasticNet with tuning, best_params: ", icv_CLF["best_params"])


# Store predictions
val_preds_df = pd.concat([
    val_preds_df,
    pd.DataFrame({
        "fold": split,
        "classifier": "Unpenalized LogisticRegression",
        "y_index": test_y.index,
        "y_true": test_y,
        "y_pred": preds_noTuning,
        "y_score": scores_noTuning,
    }),
    pd.DataFrame({
        "fold": split,
        "classifier": "ElasticNet with tuning",
        "y_index": test_y.index,
        "y_true": test_y,
        "y_pred": icv_CLF["y_pred"],
        "y_score": icv_CLF["y_score"],
    }),
])

[I 2026-05-12 00:37:08,672] A new study created in memory with name: no-name-afee69fe-e8c0-4357-abba-c20800d3bc22
[I 2026-05-12 00:37:15,306] Trial 0 finished with value: -0.3733201238467078 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.14238560101964584, 'l1_ratio': 0.9, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3733201238467078.
[I 2026-05-12 00:37:37,606] Trial 1 finished with value: -0.665925947000969 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 139.30009483752116, 'l1_ratio': 0.8, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3733201238467078.
[I 2026-05-12 00:37:51,993] Trial 2 finished with value: -0.38666773169835444 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.4425536855355255, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 0 with value: -0.3733201238467078.
[I 2026-05-12 00:37:58,074] Trial 3 finished with value: -0.33899204196194266 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.18095610633425838, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:38:19,710] Trial 4 finished with value: -0.672040431904008 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 607.5662055045161, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:38:35,534] Trial 5 finished with value: -0.5062043932514324 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 3.9396939042488777, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:38:57,270] Trial 6 finished with value: -0.6700820577560717 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 471.28858569595684, 'l1_ratio': 1.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:39:20,199] Trial 7 finished with value: -0.6711779200353744 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 590.8687416314505, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:39:42,960] Trial 8 finished with value: -0.667213158451692 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 213.7248885859839, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:39:43,542] Trial 9 finished with value: -0.5413505421834099 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.004925593549872532, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:39:43,614] Trial 10 finished with value: -0.6900324852626708 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0030775239598856167, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:39:47,032] Trial 11 finished with value: -0.3610879733645041 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.10378765415272413, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:39:49,104] Trial 12 finished with value: -0.3657052500746186 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.04843999943307408, 'l1_ratio': 0.6000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:08,374] Trial 13 finished with value: -0.5263704940951704 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 5.605161106339602, 'l1_ratio': 0.7000000000000001, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:09,618] Trial 14 finished with value: -0.38269360852238365 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.02754793964571451, 'l1_ratio': 0.5, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:18,965] Trial 15 finished with value: -0.43850348615855034 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.6625321497521084, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:26,237] Trial 16 finished with value: -0.35007523325072826 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3414034868603427, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:46,766] Trial 17 finished with value: -0.6192625092518657 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 22.08467615653412, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:47,532] Trial 18 finished with value: -0.43591773155502345 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.012680633372875874, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:47,604] Trial 19 finished with value: -0.6900977688773768 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0010217066505697672, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:40:55,619] Trial 20 finished with value: -0.3608593384280221 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.4736106964617533, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:41:04,488] Trial 21 finished with value: -0.35488048265620886 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.3995254427786942, 'l1_ratio': 0.4, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:41:11,891] Trial 22 finished with value: -0.34527231415391113 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.28075382707626445, 'l1_ratio': 0.30000000000000004, 'solver': 'saga', 'max_iter': 10000}. Best is trial 3 with value: -0.33899204196194266.
[I 2026-05-12 00:41:15,817] Trial 23 finished with value: -0.33342387981726174 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.13627338594787541, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.33342387981726174.
[I 2026-05-12 00:41:26,047] Trial 24 finished with value: -0.442369544128145 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 1.759007132691411, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 23 with value: -0.33342387981726174.
[I 2026-05-12 00:41:29,209] Trial 25 finished with value: -0.3333718254183825 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0977542863177977, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 25 with value: -0.3333718254183825.
[I 2026-05-12 00:41:30,677] Trial 26 finished with value: -0.34770612602927864 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.024245548250190596, 'l1_ratio': 0.1, 'solver': 'saga', 'max_iter': 10000}. Best is trial 25 with value: -0.3333718254183825.
[I 2026-05-12 00:41:33,607] Trial 27 finished with value: -0.33382648483709493 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0879148974663365, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 25 with value: -0.3333718254183825.
[I 2026-05-12 00:41:37,192] Trial 28 finished with value: -0.33536686076923533 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.07417550024904794, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}. Best is trial 25 with value: -0.3333718254183825.
[I 2026-05-12 00:41:38,610] Trial 29 finished with value: -0.34521045111625026 and parameters: {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.009962333424011746, 'l1_ratio': 0.0, 'solver': 'saga', 'max_iter': 10000}. Best is trial 25 with value: -0.3333718254183825.

fold: 4, classifier: Unpenalized LogisticRegression, AUROC:  0.5654761904761905
              precision    recall  f1-score   support

           0       0.93      0.88      0.90        42
           1       0.17      0.25      0.20         4

    accuracy                           0.83        46
   macro avg       0.55      0.57      0.55        46
weighted avg       0.86      0.83      0.84        46

fold: 4, classifier: ElasticNet with tuning, AUROC:  0.6904761904761905
              precision    recall  f1-score   support

           0       0.95      0.88      0.91        42
           1       0.29      0.50      0.36         4

    accuracy                           0.85        46
   macro avg       0.62      0.69      0.64        46
weighted avg       0.89      0.85      0.87        46

fold: 4, classifier: ElasticNet with tuning, best_params:  {'class_weight': 'balanced', 'penalty': 'elasticnet', 'C': 0.0977542863177977, 'l1_ratio': 0.2, 'solver': 'saga', 'max_iter': 10000}

## Session Info

In [10]:

#@title Session Info
print(sys.version)
!pip freeze

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
absl-py==1.4.0
accelerate==1.13.0
access==1.1.10.post3
affine==2.4.0
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.5
aiosignal==1.4.0
aiosqlite==0.22.1
alabaster==1.0.0
albucore==0.0.24
albumentations==2.0.8
ale-py==0.11.2
alembic==1.18.4
altair==5.5.0
annotated-doc==0.0.4
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.13.0
anywidget==0.9.21
apsw==3.53.0.0
apswutils==0.1.2
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
array_record==0.8.3
arrow==1.4.0
arviz==0.22.0
astropy==7.2.0
astropy-iers-data==0.2026.4.20.0.58.15
astunparse==1.6.3
atpublic==5.1
attrs==26.1.0
audioread==3.1.0
Authlib==1.6.11
autograd==1.8.0
babel==2.18.0
backcall==0.2.0
beartype==0.22.9
beautifulsoup4==4.13.5
betterproto==2.0.0b6
bigframes==2.39.0
bigquery-magics==0.14.0
bleach==6.3.0
blinker==1.9.0
blis==1.3.3
blobfile==3.2.0
blosc2==4.1.2
bokeh==3.8.2
Bottleneck==1.4.2
bqplot==0.12.45
branca==0.8.2
brotli==1.2.0
CacheControl==0.14.4
cachetools==6.2.6
catalogue==2.0.10
certifi==2026.4.22
cffi==2.0.0
chardet==5.2.0
charset-normalizer==3.4.7
clarabel==0.11.1
click==8.3.3
click-plugins==1.1.1.2
cligj==0.7.2
cloudpathlib==0.23.0
cloudpickle==3.1.2
cmake==3.31.10
cmdstanpy==1.3.0
colorcet==3.1.0
colorlog==6.10.1
colorlover==0.3.0
community==1.0.0b1
confection==1.3.3
cons==0.4.7
contourpy==1.3.3
cramjam==2.11.0
cryptography==43.0.3
cufflinks==0.17.3
curl_cffi==0.15.0
cvxopt==1.3.2
cvxpy==1.6.7
cycler==0.12.1
cyipopt==1.5.0
cymem==2.0.13
Cython==3.0.12
dask==2026.3.0
dataproc-spark-connect==1.1.0
datasets==4.0.0
db-dtypes==1.5.1
dbus-python==1.2.18
debugpy==1.8.15
decorator==4.4.2
defusedxml==0.7.1
deprecation==2.1.0
diffusers==0.37.1
dill==0.3.8
distro==1.9.0
dlib==19.24.6
dm-tree==0.1.10
docstring_parser==0.18.0
docutils==0.21.2
dopamine_rl==4.1.2
duckdb==1.3.2
earthengine-api==1.7.22
easydict==1.13
editdistance==0.8.1
eerepr==0.1.2
einops==0.8.2
en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl#sha256=1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85
entrypoints==0.4
esda==2.9.0
et_xmlfile==2.0.0
etils==1.14.0
etuples==0.3.10
Farama-Notifications==0.0.4
fastai==2.8.7
fastapi==0.136.1
fastcore==1.12.42
fastdownload==0.0.7
fastjsonschema==2.21.2
fastlite==0.2.4
fastprogress==1.1.5
fasttransform==0.0.2
ffmpy==1.0.0
filelock==3.29.0
fiona==1.10.1
firebase-admin==6.9.0
Flask==3.1.3
flatbuffers==25.12.19
flax==0.11.2
folium==0.20.0
fonttools==4.62.1
fqdn==1.5.1
frozendict==2.4.7
frozenlist==1.8.0
fsspec==2025.3.0
future==1.0.0
gast==0.7.0
gcsfs==2025.3.0
GDAL==3.8.4
gdown==5.2.2
geemap==0.37.2
geocoder==1.38.1
geographiclib==2.1
geopandas==1.1.3
geopy==2.4.1
giddy==2.3.6
gin-config==0.5.0
gitdb==4.0.12
GitPython==3.1.47
glob2==0.7
google==3.0.0
google-adk==1.29.0
google-ai-generativelanguage==0.6.15
google-api-core==2.30.3
google-api-python-client==2.194.0
google-auth==2.47.0
google-auth-httplib2==0.3.1
google-auth-oauthlib==1.3.1
google-cloud-aiplatform==1.148.1
google-cloud-appengine-logging==1.9.0
google-cloud-audit-log==0.5.0
google-cloud-bigquery==3.41.0
google-cloud-bigquery-connection==1.21.0
google-cloud-bigquery-storage==2.37.0
google-cloud-bigtable==2.36.0
google-cloud-core==2.5.1
google-cloud-dataplex==2.18.0
google-cloud-dataproc==5.27.0
google-cloud-datastore==2.24.0
google-cloud-discoveryengine==0.13.12
google-cloud-firestore==2.27.0
google-cloud-functions==1.23.0
google-cloud-iam==2.22.0
google-cloud-language==2.20.0
google-cloud-logging==3.15.0
google-cloud-monitoring==2.30.0
google-cloud-pubsub==2.37.0
google-cloud-resource-manager==1.17.0
google-cloud-secret-manager==2.27.0
google-cloud-spanner==3.65.0
google-cloud-speech==2.38.0
google-cloud-storage==3.10.1
google-cloud-trace==1.19.0
google-cloud-translate==3.26.0
google-colab @ file:///colabtools/dist/google_colab-1.0.0.tar.gz
google-crc32c==1.8.0
google-genai==1.68.0
google-generativeai==0.8.6
google-pasta==0.2.0
google-resumable-media==2.8.2
googleapis-common-protos==1.74.0
googledrivedownloader==1.1.0
gradio==5.50.0
gradio_client==1.14.0
grain==0.2.16
graphviz==0.21
greenlet==3.4.0
groovy==0.1.2
grpc-google-iam-v1==0.14.4
grpc-interceptor==0.15.4
grpcio==1.80.0
grpcio-status==1.71.2
grpclib==0.4.9
gspread==6.2.1
gspread-dataframe==4.0.0
gym==0.25.2
gym-notices==0.1.0
gymnasium==1.3.0
h11==0.16.0
h2==4.3.0
h5netcdf==1.8.1
h5py==3.16.0
hdbscan==0.8.42
hf-xet==1.4.3
highspy==1.14.0
holidays==0.95
holoviews==1.22.1
hpack==4.1.0
html5lib==1.1
httpcore==1.0.9
httpimport==1.4.1
httplib2==0.31.2
httptools==0.7.1
httpx==0.28.1
httpx-sse==0.4.3
huggingface_hub==1.11.0
humanize==4.15.0
hyperframe==6.1.0
hyperopt==0.2.7
ibis-framework==9.5.0
idna==3.13
ImageIO==2.37.3
imageio-ffmpeg==0.6.0
imagesize==2.0.0
imbalanced-learn==0.14.1
immutabledict==4.3.1
importlib_metadata==8.7.1
importlib_resources==7.1.0
imutils==0.5.4
inequality==1.1.2
inflect==7.5.0
iniconfig==2.3.0
intel-cmplr-lib-ur==2025.3.3
intel-openmp==2025.3.3
ipyevents==2.0.4
ipyfilechooser==0.6.0
ipykernel==6.17.1
ipyleaflet==0.20.0
ipyparallel==8.8.0
ipython==7.34.0
ipython-genutils==0.2.0
ipython-sql==0.5.0
ipywidgets==7.7.1
isoduration==20.11.0
itsdangerous==2.2.0
jaraco.classes==3.4.0
jaraco.context==6.1.2
jaraco.functools==4.4.0
jax==0.7.2
jaxlib==0.7.2
jeepney==0.9.0
jieba==0.42.1
Jinja2==3.1.6
jiter==0.14.0
joblib==1.5.3
jsonpatch==1.33
jsonpickle==4.1.1
jsonpointer==3.1.1
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
jupyter-console==6.6.3
jupyter-events==0.12.1
jupyter-leaflet==0.20.0
jupyter_client==7.4.9
jupyter_core==5.9.1
jupyter_kernel_gateway @ git+https://github.com/googlecolab/kernel_gateway@b134e9945df25c2dcb98ade9129399be10788671
jupyter_server==2.14.0
jupyter_server_terminals==0.5.4
jupyterlab_pygments==0.3.0
jupyterlab_widgets==3.0.16
jupytext==1.19.1
kaggle==2.0.2
kagglehub==1.0.0
kagglesdk==0.1.20
keras==3.13.2
keras-hub==0.26.0
keras-nlp==0.26.0
keyring==25.7.0
keyrings.google-artifactregistry-auth==1.1.2
kiwisolver==1.5.0
langchain==1.2.15
langchain-core==1.3.1
langgraph==1.1.9
langgraph-checkpoint==4.0.2
langgraph-prebuilt==1.0.10
langgraph-sdk==0.3.13
langsmith==0.7.34
lark==1.3.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy-loader==0.5
libclang==18.1.1
libpysal==4.14.1
librosa==0.11.0
lightgbm==4.6.0
linkify-it-py==2.1.0
llvmlite==0.43.0
locket==1.0.0
logical-unification==0.4.7
lxml==6.1.0
Mako==1.3.11
mapclassify==2.10.0
Markdown==3.10.2
markdown-it-py==4.0.0
MarkupSafe==3.0.3
matplotlib==3.10.0
matplotlib-inline==0.2.1
matplotlib-venn==1.1.2
mcp==1.27.0
mdit-py-plugins==0.5.0
mdurl==0.1.2
mgwr==2.2.1
miniKanren==1.0.5
missingno==0.5.2
mistune==3.2.0
mizani==0.13.5
mkl==2025.3.1
ml_dtypes==0.5.4
mlxtend==0.23.4
mmh3==5.2.1
momepy==0.11.0
more-itertools==10.8.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.1.2
multidict==6.7.1
multipledispatch==1.0.0
multiprocess==0.70.16
multitasking==0.0.13
murmurhash==1.0.15
music21==9.9.1
namex==0.1.0
narwhals==2.20.0
natsort==8.4.0
nbclassic==1.3.3
nbclient==0.10.4
nbconvert==7.17.1
nbformat==5.10.4
ndindex==1.10.1
nest-asyncio==1.6.0
networkx==3.6.1
nibabel==5.4.2
nltk==3.9.1
notebook==6.5.7
notebook_shim==0.2.4
numba==0.60.0
numexpr==2.14.1
numpy==2.0.2
nvidia-nccl-cu12==2.30.4
oauth2client==4.1.3
oauthlib==3.3.1
omegaconf==2.3.0
onemkl-license==2025.3.1
openai==2.32.0
opencv-contrib-python==4.13.0.92
opencv-python==4.13.0.92
opencv-python-headless==4.13.0.92
openpyxl==3.1.5
opentelemetry-api==1.38.0
opentelemetry-exporter-gcp-logging==1.11.0a0
opentelemetry-exporter-gcp-monitoring==1.11.0a0
opentelemetry-exporter-gcp-trace==1.11.0
opentelemetry-exporter-otlp-proto-common==1.38.0
opentelemetry-exporter-otlp-proto-http==1.38.0
opentelemetry-proto==1.38.0
opentelemetry-resourcedetector-gcp==1.11.0a0
opentelemetry-sdk==1.38.0
opentelemetry-semantic-conventions==0.59b0
opt_einsum==3.4.0
optax==0.2.8
optree==0.19.0
optuna==4.8.0
orbax-checkpoint==0.11.36
orjson==3.11.8
ormsgpack==1.12.2
osqp==1.1.1
overrides==7.7.0
packaging==26.1
pandas==2.2.2
pandas-datareader==0.10.0
pandas-gbq==0.30.0
pandas-stubs==2.2.2.240909
pandocfilters==1.5.1
panel==1.8.10
param==2.3.3
parso==0.8.6
parsy==2.2
partd==1.4.2
patsy==1.0.2
peewee==4.0.5
peft==0.19.1
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.3.0
platformdirs==4.9.6
plotly==5.24.1
plotnine==0.14.5
pluggy==1.6.0
plum-dispatch==2.8.0
pointpats==2.5.5
polars==1.35.2
polars-runtime-32==1.35.2
pooch==1.9.0
portpicker==1.5.2
preshed==3.0.13
prettytable==3.17.0
proglog==0.1.12
progressbar2==4.5.0
prometheus_client==0.25.0
promise==2.3
prompt_toolkit==3.0.52
propcache==0.4.1
prophet==1.3.0
proto-plus==1.27.2
protobuf==5.29.6
psutil==5.9.5
psycopg2==2.9.12
psygnal==0.15.1
ptyprocess==0.7.0
PuLP==3.3.0
py-cpuinfo==9.0.0
py4j==0.10.9.9
pyarrow==18.1.0
pyasn1==0.6.3
pyasn1_modules==0.4.2
pycairo==1.29.0
pycocotools==2.0.11
pycparser==3.0
pycryptodomex==3.23.0
pydantic==2.12.3
pydantic-settings==2.14.0
pydantic_core==2.41.4
pydata-google-auth==1.9.1
pydot==4.0.1
pydotplus==2.0.2
PyDrive2==1.21.3
pydub==0.25.1
pyerfa==2.0.1.5
pygame==2.6.1
pygit2==1.19.2
Pygments==2.20.0
PyGObject==3.48.2
pyiceberg==0.11.1
PyJWT==2.12.1
pymc==5.28.4
pynndescent==0.6.0
pyogrio==0.12.1
pyomo==6.10.0
PyOpenGL==3.1.10
pyOpenSSL==24.2.1
pyparsing==3.3.2
pyperclip==1.11.0
pyproj==3.7.2
pyroaring==1.0.4
pysal==25.7
pyshp==3.0.3
PySocks==1.7.1
pyspark==4.0.2
pytensor==2.38.2
pytest==8.4.2
python-apt==0.0.0
python-box==7.4.1
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-fasthtml==0.12.50
python-json-logger==4.1.0
python-louvain==0.16
python-multipart==0.0.26
python-slugify==8.0.4
python-snappy==0.7.3
python-utils==3.9.1
pytz==2025.2
pyviz_comms==3.0.6
PyWavelets==1.9.0
PyYAML==6.0.3
pyzmq==26.2.1
quantecon==0.11.2
rasterio==1.5.0
rasterstats==0.20.0
ratelim==0.1.6
referencing==0.37.0
regex==2025.11.3
requests==2.32.4
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
requirements-parser==0.9.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rich==13.9.4
roman-numerals==4.1.0
roman-numerals-py==4.1.0
rpds-py==0.30.0
rpy2==3.5.17
rsa==4.9.1
rtree==1.4.1
ruff==0.15.11
safehttpx==0.1.7
safetensors==0.7.0
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.16.3
scooby==0.11.2
scs==3.2.11
seaborn==0.13.2
SecretStorage==3.5.0
segregation==2.5.4
semantic-version==2.10.0
Send2Trash==2.1.0
sentence-transformers==5.4.1
sentencepiece==0.2.1
sentry-sdk==2.58.0
setuptools==75.2.0
shap==0.51.0
shapely==2.1.2
shellingham==1.5.4
simple-parsing==0.1.8
simplejson==4.1.0
simsimd==6.5.16
six==1.17.0
sklearn-compat==0.1.5
sklearn-pandas==2.2.0
slicer==0.0.8
smart_open==7.6.0
smmap==5.0.3
sniffio==1.3.1
snowballstemmer==3.0.1
soundfile==0.13.1
soupsieve==2.8.3
soxr==1.0.0
spacy==3.8.14
spacy-legacy==3.0.12
spacy-loggers==1.0.5
spaghetti==1.7.6
spanner-graph-notebook==1.1.10
spglm==1.1.0
Sphinx==8.2.3
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
spint==1.0.7
splot==1.1.7
spopt==0.7.0
spreg==1.9.0
SQLAlchemy==2.0.49
sqlalchemy-spanner==1.17.3
sqlglot==25.20.2
sqlparse==0.5.5
srsly==2.5.3
sse-starlette==3.3.4
stanio==0.5.1
starlette==0.52.1
statsmodels==0.14.6
strictyaml==1.7.3
stringzilla==4.6.0
stumpy==1.13.0
sympy==1.14.0
tables==3.10.2
tabulate==0.9.0
tbb==2022.3.1
tcmlib==1.4.1
tenacity==9.1.4
tensorboard==2.20.0
tensorboard-data-server==0.7.2
tensorflow==2.20.0
tensorflow-datasets==4.9.9
tensorflow-hub==0.16.1
tensorflow-metadata==1.17.3
tensorflow-probability==0.25.0
tensorflow-text==2.20.1
tensorstore==0.1.82
termcolor==3.3.0
terminado==0.18.1
text-unidecode==1.3
textblob==0.19.0
tf-slim==1.1.0
tf_keras==2.20.0
thinc==8.3.13
threadpoolctl==3.6.0
tifffile==2026.4.11
tiktoken==0.12.0
timm==1.0.26
tinycss2==1.4.0
tobler==0.14.0
tokenizers==0.22.2
toml==0.10.2
tomlkit==0.13.3
toolz==0.12.1
torch @ https://download.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
torchao==0.10.0
torchaudio @ https://download.pytorch.org/whl/cpu/torchaudio-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
torchcodec @ https://download.pytorch.org/whl/cpu/torchcodec-0.10.0-cp312-cp312-manylinux_2_28_x86_64.whl
torchdata==0.11.0
torchsummary==1.5.1
torchtune==0.6.1
torchvision @ https://download.pytorch.org/whl/cpu/torchvision-0.25.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
tornado==6.5.1
tqdm==4.67.3
traitlets==5.7.1
traittypes==0.2.3
transformers==5.0.0
treescope==0.1.10
tsfresh==0.21.1
tweepy==4.16.0
typeguard==4.5.1
typer==0.24.2
typer-slim==0.24.0
types-pytz==2026.1.1.20260408
types-setuptools==82.0.0.20260408
typing-inspection==0.4.2
typing_extensions==4.15.0
tzdata==2026.1
tzlocal==5.3.1
uc-micro-py==2.0.0
umap-learn==0.5.12
umf==1.0.3
uri-template==1.3.0
uritemplate==4.2.0
urllib3==2.5.0
uuid_utils==0.14.1
uvicorn==0.46.0
uvloop==0.22.1
vega-datasets==0.9.0
wadllib==1.3.6
wandb==0.26.1
wasabi==1.1.3
watchdog==6.0.0
watchfiles==1.1.1
wcwidth==0.6.0
weasel==1.0.0
webcolors==25.10.0
webencodings==0.5.1
websocket-client==1.9.0
websockets==15.0.1
Werkzeug==3.1.8
wheel==0.47.0
widgetsnbextension==3.6.10
wordcloud==1.9.6
wrapt==2.1.2
xarray==2025.12.0
xarray-einstats==0.10.0
xgboost==3.2.0
xlrd==2.0.2
xxhash==3.6.0
xyzservices==2026.3.0
yarl==1.23.0
ydf==0.15.0
ydf_tf==2.20.0
yellowbrick==1.5
yfinance==0.2.66
zipp==3.23.1
zstandard==0.25.0